apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app     # Must match the label in your Deployment's Pod template
  ports:
    - protocol: TCP
      port: 80          # Service port (what users connect to)
      targetPort: 5000  # Container port inside the Pod (Flask runs here)
  type: NodePort        # Expose to external network (good for testing)